[workspace]
resolver = "2"
members = [
  "crates/lib",
  "crates/yee",
  "crates/yee-diagram",
]

[workspace.dependencies]
rand = { version = "0.9.0", features = ["std_rng"] }
serde = { version = "1.0.225", features = ["derive"] }

[profile.test]
opt-level = 2
debug-assertions = true
