[package]
name = "orders"
version = "0.0.1"
edition = "2024"

[dependencies]
rand = { version = "0.9.0", features = ["std_rng"] }
rand_chacha = "0.9.0"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
